version: 2.1

jobs:
  build:
    docker:
      - image: node:alpine
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --file Dockerfile.test -t test-image:$TAG .
          docker run -t test-image:$TAG