version: 2.1

jobs:
  build:
    machine: 
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      # ... steps for building/testing app ...

      # build and push Docker image
      - run: 
          name: Build
          command: docker build --file Dockerfile.test -t test-image:0.1.$CIRCLE_BUILD_NUM .
          working_directory: app

      - run: 
          name: Test
          command: docker run -t test-image:0.1.$CIRCLE_BUILD_NUM
          working_directory: app
