version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      # ... steps for building/testing app ...

      # build and push Docker image
      - run: docker build --file Dockerfile.test -t test-image:0.1.$CIRCLE_BUILD_NUM .

      - run: docker run -t test-image:0.1.$CIRCLE_BUILD_NUM
