name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the test Docker image
      run: docker build . --file Dockerfile.test --tag test-image-name:$(date +%s)
      working-directory: app
    - name:
      run: docker run test-image-name:latest
      working-directory: app 

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  #     working-directory: app

  